# Generated by Django 4.2.2 on 2023-06-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_nmae_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nmae',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
